included:
  - Pokedex/Architecture

disabled_rules:
  - trailing_whitespace
  - leading_whitespace
  - line_length
  - identifier_name
  - type_name
  - void_function_in_ternary
  - file_length

opt_in_rules:
#  - anonymous_argument_in_multiline_closure
  - anyobject_protocol
  - attributes
  - balanced_xctest_lifecycle
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - discarded_notification_center_observer
  - discouraged_none_name
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
#  - explicit_type_interface
  - fatal_error_message
#  - file_name
  - file_name_no_space
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - implicitly_unwrapped_optional
  - indentation_width
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - let_var_whitespace
  - literal_expression_end_indentation
  - missing_docs
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - no_magic_numbers
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - raw_value_for_camel_cased_codable_enum
  - redundant_nil_coalescing
  - return_value_from_void_function
  - self_binding
  - single_test_class
  - sorted_first_last
  - strict_fileprivate
  - switch_case_on_newline
  - test_case_accessibility
  - toggle_bool
#  - trailing_closure
  - type_contents_order
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - weak_delegate
  - yoda_condition